version: "3.1"
services:
    mysql-app:
      image: mysql:5.7.22
      ports:
        - "3306:3306"
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: laravel
        MYSQL_DATABASE: trabArquitetura
      networks:
        - app-network

    laravel-app:
      build:
        dockerfile: ./Dockerfile
        context: .
      ports:
      - '8080:8080'
      depends_on:
      - mysql-app
      networks:
        - app-network
networks:
  app-network:
    driver: bridge